export const GET_CART = 'APP/CART/GET_CART';
export const ADD_TO_CART = 'APP/CART/ADD_TO_CART';
export const REMOVE_FROM_CART = 'APP/CART/REMOVE_FROM_CART';
export const UPDATE_ITEM_QUANTITY = 'APP/CART/UPDATE_ITEM_QUANTITY';
export const CLEAR_CART = 'APP/CART/CLEAR_CART';
export const PLACE_ORDER = 'APP/CART/PLACE_ORDER';
